url: https://rumnha.github.io

# Site settings
title: Rumnha
description: "Rumnha: I work on Microsoft .Net development stack"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/rumnha

# Postal address (add as many lines as necessary)
# Build settings
markdown: kramdown
permalink: pretty
